/**
 * lib/visual/visual-agent.ts
 *
 * Unified visual generation agent for social posts.
 *
 * Model selection tree:
 *   style = 'datos'          → satori          (data / chart cards)
 *   style = 'minimalista'
 *        | 'corporativo'
 *        | 'editorial'
 *        | overlayText       → fal-ai/recraft-v3  (brand / text-in-image)
 *   style = 'illustration'   → fal-ai/flux/dev    (digital illustration)
 *   style = 'photorealistic'
 *        | (default)         → fal-ai/flux-pro/v1.1-ultra (hyperrealistic photo)
 *
 * If visualDescription is empty, Claude generates one from the post context.
 * Returns 3 variations (PNG/JPEG Supabase URLs) plus metadata.
 */

import { fal }               from '@fal-ai/client'
import Anthropic             from '@anthropic-ai/sdk'
import sharp                 from 'sharp'
import { createAdminClient } from '@/lib/supabase/admin'
import { downloadFromDrive } from '@/lib/google-drive'
import { renderSatoriTemplate, SatoriTemplate } from './generators/satori-renderer'
import type { SatoriInput }  from './generators/satori-renderer'

// ─── Types ────────────────────────────────────────────────────────────────────

export interface StoredColor {
  name?  : string
  hex    : string
  role?  : string
  usage? : string
}

export interface VisualAgentInput {
  clientId         : string
  postId?          : string   // source_id for visual_generations
  platform         : string
  format           : string
  style            : string   // photorealistic | illustration | minimalista | corporativo | editorial | datos
  ratio            : string   // '1:1' | '16:9' | '9:16' | '4:5'
  visualDescription: string   // may be empty → Claude auto-generates
  includeLogo      : boolean
  overlayText      : string | null
  // Brand context (fetched by the API route before calling this)
  primaryColor?    : string
  logoAssets?      : Array<{
    drive_file_id?: string | null
    drive_url?    : string | null
  }>
  // For satori templates only
  satoriTemplate?  : SatoriTemplate
  satoriItems?     : SatoriInput['items']
  satoriDataPoint? : string
  satoriDataLabel? : string
}

export interface VisualAgentResult {
  modelUsed       : string
  modelReason     : string
  generatedPrompt : string
  variations      : string[]   // 3 public URLs (may be fewer if some calls failed)
}

// ─── Constants ────────────────────────────────────────────────────────────────

const BUCKET = 'social-assets'

const RATIO_DIMS: Record<string, { width: number; height: number }> = {
  '1:1':  { width: 1024, height: 1024 },
  '16:9': { width: 1344, height: 768  },
  '9:16': { width: 768,  height: 1344 },
  '4:5':  { width: 896,  height: 1120 },
}

const STYLE_DESCRIPTORS: Record<string, string> = {
  photorealistic: 'photorealistic, professional photography, high quality, detailed, commercial photography',
  illustration  : 'digital illustration, clean vector style, modern design, vibrant colors, artistic',
  minimalista   : 'minimalist design, clean, white space, simple geometric elements, elegant typography',
  editorial     : 'editorial photography style, magazine quality, sophisticated composition, brand aesthetic',
  corporativo   : 'corporate modern design, professional, clean layout, business aesthetic, structured',
  datos         : 'data visualization, infographic style, clean chart, modern data design',
}

const RECRAFT_STYLES: Record<string, string> = {
  minimalista : 'digital_illustration/minimalistic',
  corporativo : 'digital_illustration/corporate',
  editorial   : 'realistic_image/hard_flash',
}

// ─── Model selection ─────────────────────────────────────────────────────────

function selectModel(style: string, hasOverlayText: boolean): { model: string; reason: string } {
  if (style === 'datos') {
    return {
      model : 'satori',
      reason: 'Gráficos y datos requieren renderizado vectorial preciso con tipografía perfecta',
    }
  }
  if (hasOverlayText || style === 'minimalista' || style === 'corporativo' || style === 'editorial') {
    return {
      model : 'fal-ai/recraft-v3',
      reason: 'Diseño de marca y texto integrado en imagen — Recraft V3 optimizado para esto',
    }
  }
  if (style === 'illustration') {
    return {
      model : 'fal-ai/flux/dev',
      reason: 'Ilustración digital artística — Flux Dev genera estilos ilustrativos más creativos',
    }
  }
  return {
    model : 'fal-ai/flux-pro/v1.1-ultra',
    reason: 'Fotografía hiperrealista — Flux Pro Ultra produce la mayor calidad fotográfica',
  }
}

// ─── Auto-generate visual description via Claude ─────────────────────────────

async function autoGenerateDescription(
  platform: string,
  format  : string,
  style   : string,
): Promise<string> {
  const anthropic = new Anthropic()
  const message = await anthropic.messages.create({
    model     : 'claude-haiku-4-5',
    max_tokens: 200,
    messages  : [{
      role   : 'user',
      content: `Generate a concise, vivid visual description (2-3 sentences, English) for a ${style} style social media image for ${platform} (${format || 'post'} format).
The description should be specific enough to guide an AI image generator.
Focus on: scene/subject, lighting, composition, mood.
Output ONLY the description, no preamble.`,
    }],
  })
  const text = message.content[0]
  return text.type === 'text' ? text.text.trim() : `${style} style image for ${platform}`
}

// ─── Fal.ai generators ───────────────────────────────────────────────────────

interface FalImageResult {
  images?: Array<{ url: string }>
  image?:  { url: string }
}

async function callFalSingle(
  model        : string,
  prompt       : string,
  ratio        : string,
  style        : string,
  primaryColor?: string,
): Promise<string | null> {
  const dims = RATIO_DIMS[ratio] ?? RATIO_DIMS['1:1']
  try {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    let falResult: any

    if (model === 'fal-ai/recraft-v3') {
      const recraftStyle = RECRAFT_STYLES[style] ?? 'digital_illustration'
      const colorInput = primaryColor
        ? (() => {
            const h = primaryColor.replace('#', '')
            return [{ rgb: [
              parseInt(h.substring(0, 2), 16),
              parseInt(h.substring(2, 4), 16),
              parseInt(h.substring(4, 6), 16),
            ]}]
          })()
        : undefined

      falResult = await (fal as any).subscribe(model, {
        input: {
          prompt,
          image_size: { width: dims.width, height: dims.height },
          style     : recraftStyle,
          ...(colorInput ? { colors: colorInput } : {}),
        },
      })
    } else if (model === 'fal-ai/flux/dev') {
      falResult = await (fal as any).subscribe(model, {
        input: {
          prompt,
          image_size    : { width: dims.width, height: dims.height },
          num_images    : 1,
          output_format : 'jpeg',
          guidance_scale: 3.5,
        },
      })
    } else {
      // Default: flux-pro/v1.1-ultra
      falResult = await (fal as any).subscribe(model, {
        input: {
          prompt,
          aspect_ratio    : ratio,
          num_images      : 1,
          output_format   : 'jpeg',
          safety_tolerance: '4',
          enhance_prompt  : true,
        },
      })
    }

    const data: FalImageResult = falResult?.data ?? falResult
    return data?.images?.[0]?.url ?? (data as any)?.image?.url ?? null
  } catch (err) {
    console.error(`[visual-agent] callFalSingle error (${model}):`, err)
    return null
  }
}

async function generateFalVariations(
  model        : string,
  prompt       : string,
  ratio        : string,
  style        : string,
  primaryColor?: string,
): Promise<string[]> {
  // 3 parallel calls for variations
  const results = await Promise.all([
    callFalSingle(model, prompt, ratio, style, primaryColor),
    callFalSingle(model, prompt, ratio, style, primaryColor),
    callFalSingle(model, prompt, ratio, style, primaryColor),
  ])
  return results.filter((u): u is string => u !== null)
}

// ─── Logo composition ─────────────────────────────────────────────────────────

function escapeXml(s: string): string {
  return s
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&apos;')
}

async function composeLogo(
  imageBuffer: Buffer,
  dims       : { width: number; height: number },
  logoAssets : VisualAgentInput['logoAssets'],
  overlayText: string | null,
): Promise<Buffer> {
  const compositeInputs: sharp.OverlayOptions[] = []

  // Logo
  if (logoAssets && logoAssets.length > 0) {
    const logoAsset = logoAssets[0]
    try {
      let logoBuffer: Buffer | null = null
      if (logoAsset.drive_file_id) {
        const downloaded = await downloadFromDrive(logoAsset.drive_file_id)
        logoBuffer = Buffer.isBuffer(downloaded) ? downloaded : null
      } else if (logoAsset.drive_url) {
        const r = await fetch(logoAsset.drive_url)
        if (r.ok) logoBuffer = Buffer.from(await r.arrayBuffer())
      }
      if (logoBuffer) {
        const logoSize = Math.round(dims.width * 0.15)
        const resizedLogo = await sharp(logoBuffer)
          .resize(logoSize, logoSize, { fit: 'inside' })
          .png()
          .toBuffer()
        compositeInputs.push({
          input: resizedLogo, blend: 'over',
          top : Math.round(dims.height * 0.04),
          left: Math.round(dims.width  * 0.04),
        })
      }
    } catch (e) {
      console.warn('[visual-agent] logo composite skipped:', e)
    }
  }

  // Text overlay
  if (overlayText?.trim()) {
    const fontSize       = Math.round(dims.width * 0.045)
    const maxCharsPerLine = Math.floor(dims.width / (fontSize * 0.55))
    const words = overlayText.trim().split(' ')
    const lines: string[] = []
    let current = ''
    for (const word of words) {
      if ((current + ' ' + word).trim().length > maxCharsPerLine) {
        if (current) lines.push(current)
        current = word
      } else {
        current = current ? current + ' ' + word : word
      }
    }
    if (current) lines.push(current)

    const lineHeight = fontSize * 1.3
    const textBlockH = lines.length * lineHeight + 40
    const textBlockW = dims.width - 80
    const textSvg = `<svg width="${textBlockW}" height="${textBlockH}" xmlns="http://www.w3.org/2000/svg">
      <rect width="${textBlockW}" height="${textBlockH}" rx="8" fill="rgba(0,0,0,0.55)" />
      ${lines.map((line, i) => `<text x="${textBlockW / 2}" y="${24 + (i + 1) * lineHeight - fontSize * 0.2}"
        text-anchor="middle" font-family="sans-serif" font-size="${fontSize}"
        font-weight="bold" fill="white">${escapeXml(line)}</text>`).join('')}
    </svg>`
    compositeInputs.push({
      input: Buffer.from(textSvg),
      left : 40,
      top  : dims.height - Math.round(textBlockH) - Math.round(dims.height * 0.06),
    })
  }

  if (compositeInputs.length === 0) return imageBuffer

  return Buffer.from(
    await sharp(imageBuffer)
      .resize(dims.width, dims.height, { fit: 'cover' })
      .png()
      .composite(compositeInputs)
      .flatten({ background: { r: 255, g: 255, b: 255 } })
      .jpeg({ quality: 90 })
      .toBuffer()
  )
}

// ─── Storage helpers ──────────────────────────────────────────────────────────

async function ensureBucket(supabase: ReturnType<typeof createAdminClient>) {
  const { data: buckets } = await supabase.storage.listBuckets()
  if (!buckets?.some(b => b.name === BUCKET)) {
    await supabase.storage.createBucket(BUCKET, {
      public: true, fileSizeLimit: 20 * 1024 * 1024,
    }).catch(() => {})
  }
}

async function uploadBuffer(
  supabase  : ReturnType<typeof createAdminClient>,
  buf       : Buffer,
  path      : string,
  contentType = 'image/jpeg',
): Promise<string | null> {
  const { error } = await supabase.storage.from(BUCKET).upload(path, buf, { contentType, upsert: true })
  if (error) { console.error('[visual-agent] upload error:', error.message); return null }
  const { data: { publicUrl } } = supabase.storage.from(BUCKET).getPublicUrl(path)
  return publicUrl
}

// ─── Main entry point ─────────────────────────────────────────────────────────

export async function runVisualAgent(inp: VisualAgentInput): Promise<VisualAgentResult> {
  const supabase   = createAdminClient()
  const dims       = RATIO_DIMS[inp.ratio] ?? RATIO_DIMS['1:1']
  const primaryHex = inp.primaryColor ?? '#1A56FF'

  // 1. Select model
  const hasOverlay = !!(inp.overlayText?.trim())
  const { model, reason } = selectModel(inp.style, hasOverlay)

  // 2. Resolve / auto-generate visual description
  let description = inp.visualDescription?.trim()
  if (!description) {
    description = await autoGenerateDescription(inp.platform, inp.format, inp.style)
  }

  // 3. Build final prompt
  const styleDesc    = STYLE_DESCRIPTORS[inp.style] ?? STYLE_DESCRIPTORS.photorealistic
  const basePrompt   = description
  const styledPrompt = model !== 'satori'
    ? [
        basePrompt,
        `Style: ${styleDesc}.`,
        primaryHex ? `Primary accent color: ${primaryHex}.` : '',
        `Platform: ${inp.platform}, format: ${inp.format || 'post'}.`,
        'No text, no logos, no watermarks. High quality, professional content marketing image.',
      ].filter(Boolean).join(' ')
    : basePrompt

  // 4. Generate variations
  await ensureBucket(supabase)
  const sourceSlug = inp.postId ?? 'manual'
  let variationUrls: string[] = []

  if (model === 'satori') {
    // Render 3 satori PNG buffers with slight bg variation
    const template = inp.satoriTemplate ?? 'editorial_post'
    const satoriBase: SatoriInput = {
      template,
      width       : dims.width,
      height      : dims.height,
      primaryColor: primaryHex,
      bgColor     : '#FFFFFF',
      textColor   : '#111827',
      headline    : description || undefined,
      dataPoint   : inp.satoriDataPoint,
      dataLabel   : inp.satoriDataLabel,
      items       : inp.satoriItems,
    }
    const bgVariants = ['#FFFFFF', '#F9FAFB', primaryHex + '18']
    const buffers = await Promise.all(
      bgVariants.map(bg => renderSatoriTemplate({ ...satoriBase, bgColor: bg }).catch(() => null))
    )
    for (let i = 0; i < buffers.length; i++) {
      const buf = buffers[i]
      if (!buf) continue
      const path = `${inp.clientId}/${sourceSlug}/v${i + 1}-${Date.now()}.png`
      const url  = await uploadBuffer(supabase, buf, path, 'image/png')
      if (url) variationUrls.push(url)
    }
  } else {
    // Fal.ai: 3 parallel single-image calls
    const falUrls = await generateFalVariations(model, styledPrompt, inp.ratio, inp.style, primaryHex)

    for (let i = 0; i < falUrls.length; i++) {
      const falUrl = falUrls[i]
      try {
        const r = await fetch(falUrl)
        if (!r.ok) continue
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        let buf: Buffer = Buffer.from(await r.arrayBuffer() as ArrayBuffer) as any

        // Compose logo / text overlay
        if (inp.includeLogo || hasOverlay) {
          buf = await composeLogo(buf, dims, inp.logoAssets, inp.overlayText ?? null) as Buffer
        } else {
          // Just resize/normalise
          buf = Buffer.from(
            await sharp(buf)
              .resize(dims.width, dims.height, { fit: 'cover' })
              .jpeg({ quality: 90 })
              .toBuffer()
          )
        }

        const path = `${inp.clientId}/${sourceSlug}/v${i + 1}-${Date.now()}.jpg`
        const url  = await uploadBuffer(supabase, buf, path, 'image/jpeg')
        if (url) variationUrls.push(url)
      } catch (e) {
        console.error(`[visual-agent] post-process variation ${i + 1}:`, e)
      }
    }
  }

  return {
    modelUsed      : model,
    modelReason    : reason,
    generatedPrompt: styledPrompt,
    variations     : variationUrls,
  }
}
